remote_theme: just-the-docs/just-the-docs
repository: OpenGolfSim/opengolfsim.com
# theme: just-the-docs
logo: "/assets/logo-clear-white.svg"
color_scheme: ogs

footer_content: 'Copyright &copy; 2025 OpenGolfSim LLC - <a href="/privacy">Privacy</a> - <a href="/terms">Terms and Conditions</a>'
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

show_excerpts: true

aux_links:
  # Shop:
  #   - https://opengolfsim.com
  Contact Us:
    - /contact

exclude: [brian, .vscode, _site]
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1"

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  error:
    title: Error
    color: red
